### ISSUE TITLE
Support alternative incantations

### ISSUE THREAD

**Issue by orta** [pdcgomes/XCActionBar#1]
Ideally, I'd like to be able to activate in a way similar to AppCode, by double tapping `cmd`. But I'd happily accept being able to open `shift + space`. Any plans for a settings page?

**Comment by pdcgomes** [comment]
Yep, it's on my list -- I'll probably start by providing just a config file and later might supply UI as well. Stay tuned :)

**Comment by pdcgomes** [comment]
May need a bit more testing but there's preliminary support for "double" and "triple" tap incantations, you can configure the repeat count, delay and modifier key (cmd, alt, shift, control)

Default config: 
- double tap `CMD` to present/dismiss action bar
- double tap `ALT` to repeat last action

Let me know what you think.
