### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by royherma** [pdcgomes/XCActionBar#18]
Sorry, this might be really obvious, but I've never installed any XC plug-ins before - how do you install this one? Couldn't find any instructions or a .pbplugin file to import, so any help would be fantastic. Thanks!

**Comment by pdcgomes** [comment]
The absolute quickest and simplest way to install Xcode plugins is to do it via [Alcatraz](http://alcatraz.io/) -- an unofficial Xcode package manager.

Just follow their instructions to install it and, once you're done, you'll be able to install `XCActionBar` via a nice and simple user interface.

Hope this helps.

**Comment by royherma** [comment]
definitely helps, ill take a look! thanks :)
