### ISSUE TITLE
Doubling, fake shortcuts and floating

### ISSUE THREAD

**Issue by cojoj** [pdcgomes/XCActionBar#2]
I've decided to give it a try and I'm more than happy with this! Anyway, I've found some _bugs_ I'd like to point for the future improvements.  

First of all, when menu option has no shortcut assigned to it in `XCActionBar` dropdown menu it's still presented with the **⌘** shortcut... Why?
![fake shortcuts](https://cloud.githubusercontent.com/assets/4522407/6719061/842f1c78-cdb8-11e4-8ece-154f19112fba.png)

Another thing is that the plugin is doubling some menu entries like on the screenshot below:
![doubling](https://cloud.githubusercontent.com/assets/4522407/6718961/d4ffadbc-cdb7-11e4-969f-ef52b05ff130.png)
But I've noticed that's becuase I've got another plugin which serves the same featue... It's a little bit confusing.

Last thing is that the `XCActionBar` is not always displayed in the same place. One time it's higher but the other time is lower.

**Comment by pdcgomes** [comment]
Hey! Glad you're enjoying it!

I really appreciate the time you took to document these issues (a couple of them I had already logged as well). I'll get them sorted over the next few days, so stay tuned :)

**Comment by pdcgomes** [comment]
So, I've fixed a couple of these issues:
- Items that represent sub-menus (like `Navigators`, `Utilities`, etc. have been removed from the index (but their children are still indexed);
- Invalid shortcuts are no longer displayed
- Also fixed the "jumping" action bar
