### ISSUE TITLE
Support Editor menu in Interface Builder

### ISSUE THREAD

**Issue by onmyway133** [pdcgomes/XCActionBar#21]
When using Interface Builder (Xib, Storyboard), we use Pin, Align, ... alot. It would be great if XCActionBar could support them. Or guideline about how make contribution (understand the code) is appreciated

**Comment by pdcgomes** [comment]
Yep, it's on my todo list:

The main problem right now is that the menu bar actions are only indexed when Xcode is launched and although I do have the hooks in place to update the index when the menu bar changes, I still haven't gotten around to ensure it's working properly (and obviously it isn't :) ).

The good news is that it's one of the next things on my TODO list, so stay tuned!

**Comment by onmyway133** [comment]
I'm excited by that news. And thanks to your plugin, my plugin XCodeWay https://github.com/onmyway133/XcodeWay can be used more easily

**Comment by pdcgomes** [comment]
So, I've had a quick first pass at this and it seems to do the job quite well :)
When you switch around from different files and to <-> from interface builder, the actions for the editor menu are updated accordingly. 
This is currently **not active** for other menu items.

Give it a try and let me know if it's working out for you.
Thanks!

**Comment by onmyway133** [comment]
Seems to work for me. After I switch to storyboard, it shows the command for the Editor menu
