### ISSUE TITLE
Not working on Xcode 5

### ISSUE THREAD

**Issue by pranav-prakash** [pdcgomes/XCActionBar#26]
It doesn't seem to work using Xcode 5 as a target on Mavericks 10.9.

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
ProductBuildVersion: 5B1008
UNCAUGHT EXCEPTION (NSInvalidArgumentException): -[IDEIndex workspace]: unrecognized selector sent to instance 0x7fba991998d0
UserInfo: (null)
Hints: None

**Comment by pdcgomes** [comment]
There are currently no plans to support versions prior to 6.0 - the plugin just wasn't built with older versions in mind.
Sorry about that!
