### ISSUE TITLE
Some Actions not found with XCode 6.3.2

### ISSUE THREAD

**Issue by jaenthemaen** [pdcgomes/XCActionBar#28]
I'm unable to find features like renaming, find & replace or extraction with XCActionBar since I upgraded to XCode 6.3.2. Does anyone else have this issue or is it just my setup?

I re-installed XCActionBar just this morning.

![bildschirmfoto 2015-05-20 um 12 40 25](https://cloud.githubusercontent.com/assets/1032098/7723988/88a392d2-feed-11e4-87ed-0399ecaec1d5.png)

**Comment by pdcgomes** [comment]
Yep, I'm having the same issue - will look into it later today.

**Comment by pdcgomes** [comment]
This affected _all_ menu bar actions - I've pushed a temporary fix but I need to spend some more time on this as it's not very robust. Let me know if it's working for you.

**Comment by jaenthemaen** [comment]
Very nice! All actions that I have been missing are now back at hand. As for now, no crash happened. Cheers to you!
