### ISSUE TITLE
Xcode 6.4 installation bug

### ISSUE THREAD

**Issue by rock88** [pdcgomes/XCActionBar#29]
Hi,
I trying install XCActionBar over script 
`curl -fsSL https://raw.githubusercontent.com/pdcgomes/XCActionBar/master/Scripts/install.sh | sh`
after restart Xcode nothing happens, in Window menu doesn't appear Action bar item and key combination doesn't work.

**Comment by pdcgomes** [comment]
Hi, I hadn't updated it to support Xcode 6.4's UUID yet. Should be fixed now, can you please try?

**Comment by rock88** [comment]
@pdcgomes, now all ok, thanks for very quick help!

**Comment by pdcgomes** [comment]
:beers:
