### ISSUE TITLE
Multi Screen Support

### ISSUE THREAD

**Issue by jstart** [pdcgomes/XCActionBar#3]
Love the project, super cool idea. Found one bug. When using Xcode on a separate display, the Action Bar appears over the first display, and the actions will not execute.
![screenshot 2015-03-18 14 05 29](https://cloud.githubusercontent.com/assets/108218/6719465/fe7b099c-cd77-11e4-9665-7e857554b36e.png)

**Comment by pdcgomes** [comment]
Thanks a lot! I'm glad you're enjoying it.
Yep, I'm actually away from the office so I've only been working on my laptop (don't have a second screen until tomorrow), but I knew about this -- should be simple to address, I'll try to get to it tomorrow.

Cheers!

**Comment by jstart** [comment]
Made this PR as an attempt to fix it. 
https://github.com/pdcgomes/XCActionBar/pull/4

No rush!  Thanks again for all your work!

**Comment by pdcgomes** [comment]
The action bar should now be correctly positioned when you try to present it from a separate screen. Let me know how it's working out for you :)
