### ISSUE TITLE
Is there a way to disable double CMD shortcut?

### ISSUE THREAD

**Issue by fcy** [pdcgomes/XCActionBar#30]
I'm really enjoying the action bar but is there a way to disable the CMD+CMD shortcut?

When I hit CMD+something twice, in the second time the action bar appears. This could be because I use Keyboard Maestro to simulate/remap  actions, for example Save All when I hit CMD+S. (Yes I could change the shortcut in Xcode but with Keyboard Maestro all my changes are kept in sync between the Macs I use).

(As a power user of App Code this plugin is one of the few that makes Xcode nice to use again)

**Comment by pdcgomes** [comment]
Hi there - glad to know you're enjoying the plugin!

As for your question: currently there's no settings UI, but there is a non-documented way of doing what you're asking:

Open the plugin's resources folder (normally under `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XCActionBar.xcplugin/Contents/Resources`) and find the `XCActionBarConfiguration.plist` file. Open it and look for the following directives:
- `Shortcuts/XCActionBarHotKey`
- `Shortcuts/XCActionBarRepeatLastActionHotKey`

The first one configures the hot key for presenting/dismissing the action bar. The other one configures the hot key to repeat the last executed action (by default it's mapped to OPTION+OPTION).

To disable them, just change the `XCHotKeyListenerRepeatCount` value to `0` and restart Xcode.
If you're only interested in disabling the CMD+CMD shortcut, then you only need to change the value for `Shortcuts/XCActionBarHotKey`.

Let me know if this solved it for you.
Cheers.

**Comment by fcy** [comment]
That worked. Thanks!
