### ISSUE TITLE
Unable to launch with double tapping CMD or CMD + SHIFT + 8 using Xcode 7.1

### ISSUE THREAD

**Issue by bsrz** [pdcgomes/XCActionBar#31]

**Comment by jkyin** [comment]
same too.

**Comment by pdcgomes** [comment]
Should be fixed, just needed to declare compatibility with Xcode 7.1's UUID.
Let me know if the latest update has fixed it.

Thanks!

**Comment by jkyin** [comment]
https://github.com/pdcgomes/XCActionBar/commit/b0d6eb6173fd1412c73734953269fc178e5faf34 works. 

Thank you.

**Comment by pdcgomes** [comment]
:beers:
