### ISSUE TITLE
XCActionBar appears using other shortcuts

### ISSUE THREAD

**Issue by ignazioc** [pdcgomes/XCActionBar#32]
The actionbar appears using different shortcuts, for example using <kbd>cmd</kbd><kbd>c</kbd>  +   <kbd>cmd</kbd><kbd>v</kbd>

Is there any way to disable the <kbd>cmd</kbd><kbd>cmd</kbd> shortcut?

**Comment by pdcgomes** [comment]
Take a look at issue #30, which explains how to disable the "double tap" shortcuts.
Perhaps in the future I'll add some configuration UI to control these things.

Let me know if this solved it for you.
Thanks for using XCActionBar!

**Comment by ignazioc** [comment]
:+1:
