### ISSUE TITLE
Alcatraz support

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [pdcgomes/XCActionBar#7]
Please add this to [Alcatraz](https://github.com/supermarin/Alcatraz).

**Comment by jstart** [comment]
Uhm, it is? 
![screenshot 2015-03-19 23 06 12](https://cloud.githubusercontent.com/assets/108218/6746848/a3da48a2-ce8c-11e4-9801-90d2a4487a5b.png)

**Comment by Isuru-Nanayakkara** [comment]
Oh sorry.
