### ISSUE TITLE
Activation shortcut

### ISSUE THREAD

**Issue by eimantas** [pdcgomes/XCActionBar#9]
Would it make sense to make shortcut's reachability better? Cmd+Shift+8 doesn't look very comfortable to me (even after trying it a few times). Maybe something closer to Xcode's "Open Quickly..."? Like Alt+Shift+O?

**Comment by iv-mexx** [comment]
You can change the shortcut via the _Keyboard Shortcuts_ System Preference like explained [here](https://github.com/fortinmike/XcodeBoost) in the installation section. Maybe this should go into the Readme of this project as well...?

**Comment by eimantas** [comment]
Thanks for the tip. It probably could be included into readme.

**Comment by pdcgomes** [comment]
As an alternative you can also use double press the `CMD` key to present/dismiss the action bar, and double press the `ALT` key to repeat the last action. These shortcuts can also be configured, but the process is slightly different.

The documentation has been updated to reflect this.
